apiVersion: apps/v1
kind: Deployment
metadata:
  name: varowner-doggos
  labels:
    app: doggos
    owner: varowner
spec:
  selector:
    matchLabels:
      app: doggos
      owner: varowner
  template:
    metadata:
      labels:
        app: doggos
        tier: web
        owner: varowner
    spec:
      containers:
      - name: doggos
        image: gcr.io/windmill-public-containers/servantes/doggos:varowner-dev
        command: ["/go/bin/doggos"]
        env:
        - name: TEMPLATE_DIR
          value: "/go/src/github.com/windmilleng/servantes/doggos/web/templates"
        ports:
        - containerPort: 8083
        resources:
          requests:
            cpu: "10m"
