apiVersion: apps/v1
kind: Deployment
metadata:
  name: varowner-hypothesizer
  labels:
    app: hypothesizer
    owner: varowner
spec:
  selector:
    matchLabels:
      app: hypothesizer
      owner: varowner
  template:
    metadata:
      labels:
        app: hypothesizer
        tier: web
        owner: varowner
    spec:
      containers:
      - name: hypothesizer
        image: varimgname
        command: ["python", "/app/app.py"]
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: varowner-hypothesizer
  labels:
    app: hypothesizer
    owner: varowner
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: hypothesizer
    owner: varowner
