apiVersion: apps/v1
kind: Deployment
metadata:
  name: varowner-words
  labels:
    app: words
    owner: varowner
spec:
  selector:
    matchLabels:
      app: words
      owner: varowner
  template:
    metadata:
      labels:
        app: words
        tier: web
        owner: varowner
    spec:
      containers:
      - name: words
        image: gcr.io/windmill-public-containers/servantes/words:varowner-dev
        command: ["python", "/app/app.py"]
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "10m"
